apiVersion: v1
kind: Pod
metadata:
  name: kubia-label-selector
spec:
  nodeSelector:
    env_role: "bj"
    test: "v2"
  containers:
  - image: johnathan1874/kubia:1.0.0
    name: my-kubia-selector
    ports:
    - containerPort: 8080
      protocol: TCP
