apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:
    creation_method: manual
    env: prod
    app: test
spec:
  containers:
  - image: johnathan1874/kubia:1.0.0
    name: my-kubia-label
    ports:
    - containerPort: 8080
      protocol: TCP
