apiVersion: v1
kind: Pod
metadata:
  name: ngx-pod-check

spec:
  volumes:
  - name: ngx-conf-vol
    configMap:
       name: ngx-check-conf
  containers:
  - image: nginx:alpine
    name: ngx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: ngx-conf-vol
    
    startupProbe:
      periodSeconds: 1
      exec:
        command: ["cat", "/var/run/nginx.pid"]

    livenessProbe:
      periodSeconds: 10
      tcpSocket:
         port: 80

    readinessProbe:
      periodSeconds: 10
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      httpGet:
        path: /ready
        port: 80
