apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-ns-qt
  namespace: dev-ns
  
spec:
  hard:
    requests.cpu: 10
    requests.memory: 10Gi
    limits.cpu: 10
    limits.memory: 20Gi

    requests.storage: 100Gi
    persistentvolumeclaims: 100

    pods: 200
    configmaps: 300
    secrets: 300
    services: 20

    count/jobs.batch: 5
    count/cronjobs.batch: 5
    count/deployments.apps: 20
