apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: kubia-dep
  name: kubia-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubia-dep
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: kubia-dep
    spec:
      containers:
      - image: johnathan1874/kubia:1.0.0
        name: kubia
        resources: {}
status: {}
